### PR TITLE
Mark KER 1.1.9.4 and lower as conflicting

### PR DESCRIPTION
**Pull request by Clayell**
KER 1.1.9.5 (https://github.com/jrbudda/KerbalEngineer/releases/tag/1.1.9.5) is finally compatible with RP-1, as the pull request that adds compatibility with Real Fuels has been merged. I'm not sure if this fixes the incorrect delta-v values, but it should fixes the crashes, and KER has many other features that other mods do not have.

### CODE REVIEW

**Comment by siimav** [comment]
I disagree with KER being a rec. We already have MJ and running both at the same time isn't advised.

**Comment by Clayell** [comment]
Fair, we can have different opinions on whether or not KER is recommended (I personally find it indispensable). I'll just make it so the newest version no longer conflicts.

**Comment by HebaruSan** [comment]
> I disagree with KER being a rec. We already have MJ and running both at the same time isn't advised.

What about

```yaml
recommends:
  - any_of:
    - MechJeb2
    - KerbalEngineerRedux
```

I _think_ those would show up with only one checked by default.

**Comment by Clayell** [comment]
Well, to be fair, mechjeb is far more essential than KER, because it has ascent guidance and such. I wouldn't want to run RP-1 without either.

**Comment by NathanKell** [comment]
(This is already merged, but: for the record, MJ has a bunch of stuff that makes it a required mod for the express install. I would not suggest having it anything other than a dep.)

**Comment by Clayell** [comment]
image
Just noticed this, is this a ckan bug? Visually it looks like 1.1.9.5 is conflicting, but when hovering over it you can tell that its only 1.1.9.4 and below.

**Comment by vortexcv** [comment]
Can we add KER as a suggestion instead of recommended for express install?
Many of QOL extra mods show up as a suggestion in express install on ckan. This way it doesn't have to be mandatory for a fresh install of rp1.

**Comment by Clayell** [comment]
> Can we add KER as a suggestion instead of recommended for express install? Many of QOL extra mods show up as a suggestion in express install on ckan. This way it doesn't have to be mandatory for a fresh install of rp1.

Fair point. We should at least mark it as "supports".

**Pull request merged**
